### ISSUE TITLE
CI target architectures for libuv

### ISSUE THREAD

**Issue by rvagg** [iojs/build#14]
Continued from https://github.com/libuv/libuv/issues/12 also see #1 for additional context.

Here's a strawman proposal for architectures libuv should be tested against. They are split in to 3 classes mainly based on how difficult they will be to set up and include in the build set and how important they are to have solidly tested builds against.

--------------------------------------------------

**Class A**

  * CentOS 6 64-bit (EL6)
  * CentOS 6 32-bit (EL6)
  * CentOS 7 64-bit (EL7)
  * Ubuntu 10.04 LTS (Lucid Lynx) 64-bit
  * Ubuntu 10.04 LTS (Lucid Lynx) 32-bit
  * Ubuntu 12.04 LTS (Precise Pangolin) 64-bit
  * Ubuntu 12.04 LTS (Precise Pangolin) 32-bit
  * Ubuntu 14.04 LTS (Trusty Tahr) 64-bit
  * Ubuntu 14.04 LTS (Trusty Tahr) 32-bit
  * Ubuntu 14.10 (Utopic Unicorn) 64-bit
  * Debian stable (wheezy) 64-bit
  * Debian stable (wheezy) 32-bit
  * Windows Server 2008 R2 + Visual C++ 2012 64-bit
  * Windows Server 2008 R2 + Visual C++ 2012 32-bit
  * Windows Server 2012 R2 + Visual C++ 2013 64-bit
  * Windows Server 2012 R2 + Visual C++ 2013 32-bit
  * Mac OS X 10.8 (Mountain Lion) + XCode 5
  * Mac OS X 10.9 (Mavericks) + XCode 5
  * Mac OS X 10.10 (Yosemite) + XCode 6

**Class B**

  * CentOS 5 64-bit (EL5)
  * CentOS 5 32-bit (EL5)
  * SmartOS
  * ARMv6 32-bit (Linux)
  * ARMv7 32-bit (Linux)
  * ARMv8 32-bit (Linux, one day, when suitable hardware & OS is available)
  * ARMv8 64-bit (Linux, one day, when suitable hardware & OS is available)
  * FreeBSD stable/9 *(maybe)*
  * FreeBSD stable/10

**Class C**

  * MinGW 32-bit
  * MinGW 64-bit
  * POWER8

--------------------------------------------------

The open questions, for me at least, are:

* What build configurations are acceptable here? Is it good enough to build `debug` and test that in all cases or do we need some testing of `release` builds somewhere?
* Windows support: what is expected of libuv by its various consumers? We are being pushed in to MSVC2013 territory for Node.js because of the upstream adoption of C++11 by V8 but this is obviously not the case for libuv, so how much depth is needed there and are the MinGW builds still important (initially proposed in #1).

Are there any concerns here held by the libuv team? / @indutny @saghul @bnoordhuis @piscisaureus (I'm guessing here at who constitutes libuv-core btw).

**Comment by bnoordhuis** [comment]
Closing, I think we've implemented most of what is discussed here.  Testing with older compilers is maybe the exception but that hasn't been a problem so far.  I'll file a separate issue for that when it becomes a problem.
