### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by rvagg** [iojs/build#15]
I'm making an issue here mainly to collect names of people who can legitimately help with making Windows a first-class citizen. It's such a different beast that it really requires people who spend their time in it and understand the ecosystem rather than drop-ins (like me) who make do with their historic knowledge and occasional googling.

Examples of things that we need people for:

1. We're heading in to a place where we can only build with C++11 capable compilers, which is only MSVC 2013 on the official end (and 2015 when it's properly released). What are the implications of this for Windows build platform support (currently I only have Windows 2012 in the node-forward build cluster) and what are the implications for our ability to produce binaries that support older versions of Windows?
1. There has been some discussion of moving to clang at some point but apparently it's not quite "ready", is anybody following this? Do we have any clue about our ability to even start testing with it?
1. Fixing minor bugs in core and keeping the test suite solid and relevant for Windows. Consider the [test-cluster-eaccess.js](https://github.com/joyent/node/blob/master/test/simple/test-cluster-eaccess.js) example--originally implemented for non-Windows only but was then expanded to work on Windows but tested something completely different on Windows because of the nature of named pipes. It has since been [changed in io.js](https://github.com/iojs/io.js/blob/v0.12/test/simple/test-cluster-eaccess.js) but only because it was noticed while tracking down unrelated problems.

**Comment by bnoordhuis** [comment]
I'm going to tentatively close this now that we have @iojs/platform-windows and are getting close to zero test failures on Windows.

@springmeyer Let me know if you're still interested in helping out and I'll add you to the Windows team.
