### ISSUE TITLE
First io.js release build plan / discussion

### ISSUE THREAD

**Issue by rvagg** [iojs/build#18]
Things we need to make a first _official_ io.js release in mid January (this is top of my head, please contribute if you see something that I don't have).

**Target**

At a minimum we need to release a solid source tarball that's tested, tagged and good to compile and use as a fully compatible version of joyent/node, v0.12-worthy. Version will be `1.0.0`, perhaps with an `-alpha.x` suffix, that'll be up to the TC.

Binaries would be good but may be practical only for Linux at this stage in lieu of signing keys.

**Need**

- [ ] OSX 10.10 and 10.9 hooked up to CI (Voxer has machines ready for us to hook up, we just need to do some VM work) - @ryanstevens is responsible for this, @rvagg to work with him to make this happen
- [ ] CentOS5 hooked up to CI to ensure RHEL5-level compatibility (yak shaving abounds here) - @rvagg responsible for this, I believe I have a good strategy after shaving the RHEL6 yak with C++11

**Nice but not essential**

- [ ] OSX 10.8 hooked up to CI
- [ ] At least one version of FreeBSD hooked up to CI (Voxer has the hardware on offer for this)
- [ ] A Solaris-ish machine hooked up to CI, what are the chances of Joyent offering a box?
- [ ] Signing keys for io.js org so we can release proper Mac and Windows binaries
- [ ] Linux releases via deb.nodesource.com and rpm.nodesource.com (or similar hosts if not the same hosts) - @rvagg to work with @chrislea to make this happen

**Decisions**

- [ ] Do we mark Linux packages as "conflicting" with "nodejs" or set up an "alternatives" style system? (I know it's doable on Debian-based systems but am vague on RHEL/Fedora-based systems here)
- [ ] Exact version, up to TC, not an urgent decision
- [ ] How are tarballs named and hosted, straight from GitHub?

**Comment by stryju** [comment]
Hey guys!

Any progress re: Debian packages?

**Comment by chrislea** [comment]
We are working on them. Support for the current Debian stable (wheezy) is a godawful PITA because the compiler it ships with is too old to build iojs. And backporting a newer compiler brings its own headaches. So once we have that planned / sorted out we'll get packages built.

**Comment by stryju** [comment]
sweet! thanks for taking the time to reply :-)

**Comment by ianare** [comment]
Hi all, any plans for a CentOS 7 packages?

I would  think this would be easier than 5/6 due to the newer compiler and systemd...
There are node packages also which could be used for inspiration.

In any case, excited about all the hard work done on this project, keep it up!

**Comment by Fishrock123** [comment]
@rvagg looks like some of this is done? :)

**Comment by stryju** [comment]
can we get a small update on what was achieved from the list?

**Comment by rvagg** [comment]
Sorry! I've ticked some things off, but here's things that weren't achieved:

* OS X CI machines are only 10.10. I have a 10.9 _image_ I might ship over to the CI machines but I have no way of getting hold of a 10.8. If anyone has ideas on how to get installation media for a virtual machine for 10.9 or 10.8 that would be greatly appreciated. Apple make this way too hard (and I don't understand why nerds embrace them so much!)
* Linux releases are not being made available as .deb or .rpm _yet_. @chrislea is working on this but it's a non-trivial task. Expect news on this very soon though.
* Solaris-variant is not being tested in any way and this doesn't appear to be missed. From memory there has only been one Solaris-related issue on the io.js issue tracker and that was simply about DTrace on an Illumos variant, by @no9.

**Comment by stryju** [comment]
thanks for taking the time to reply, @rvagg! :beers: 

---

would be great to have it as a summary @ top - WDYT?

**Comment by No9** [comment]
@rvagg Initial thread was DTrace compiling on FreeBSD 

Problem I have is that my running illumOS instances are all 4.6.4 GCC and so iojs wouldn't build. 

I can take the razor to that hirsuit mammal if there is we want to provide a SmartOS build but I don't know how much bandwidth I would need to give to integrate with CI

**Comment by rvagg** [comment]
@no9 it's not really a technical problem but a resourcing one, we don't have the ability to provision solaris-variant machines at the moment, none of the providers we're working with have that capability and nobody has expressed an interest in providing it. I'm not too fussed at this point, I don't think it's in our target audience at this stage.

**Comment by No9** [comment]
@rvagg ok ill leave this for now then. 
If someone shows up with the need and we need to dig in you know where I am.

**Comment by jgrund** [comment]
Hi, Is there still an io.js rpm in the works?

**Comment by rvagg** [comment]
@jgrund yes, over @ https://github.com/nodesource/distributions

we're having some complications in getting everything up and working properly across all our supported platforms given the new complexity in the versions we're supporting but we're now in the process of throwing more people at this.

**Comment by stryju** [comment]
thanks for the update @rvagg

**Comment by StefanoBalocco** [comment]
Any news about a (maybe official) debian (jessie) package?

**Comment by ripper2hl** [comment]
iojs.rpm ?  D:
