### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by rvagg** [iojs/build#2]
I believe ARM is an important target but I'm unsure the best way to tackle CI with it. We either need to find some beefy ARM cpus somewhere that don't take 12h to compile Node or do a cross-compile then push to actual boxes to test or a distcc as @mmalecki has suggested or perhaps some crazy virtualization?

Need some input from cleverer people than me on this.

/cc @wolfeidau

**Comment by bnoordhuis** [comment]
Closing, we have ARM machines (including arm64 - woo!) hooked up.

**Comment by wolfeidau** [comment]
:+1: awesome effort!
