### ISSUE TITLE
Releases: Provide parsable catalog files of releases

### ISSUE THREAD

**Issue by rvagg** [iojs/build#22]
Continuing iojs/io.js#40 here. The summary is that to help version managers do their job with io.js we need to provide parsable catalog files detailing what releases are available (and perhaps other metadata).

Suggestion for now is to provide both a simple .txt file list in the same directory as release tarballs as well as a .json file that is extensible so we can put in additional metadata like shasums. See the comments in iojs/io.js#40 for some great ideas.

The build team need to come up with a proposal for how it'll work before passing it back to the TC for acceptance. Be sure to include other interested parties in the discussion.

/ @smikes @ljharb @kenperkins @alexgorbatchev @keithamus @naholyr @mostman79  @gkatsev @Fishrock123 @arb

**Comment by rvagg** [comment]
I've created an initial format for a catalogue, currently on nightlies but will also be on dist: [index.json](https://iojs.org/download/nightly/index.json) and [index.tab](https://iojs.org/download/nightly/index.json)

I'd really like feedback from version-manager authors on this, discussion happening in https://github.com/iojs/io.js/issues/301#issuecomment-69699195 for now

/cc @aaronpowell

**Comment by jbergstroem** [comment]
@rvagg fyi, minor miss: you linked index.json to index.tab and the other way around.

**Comment by rvagg** [comment]
derp, fixed

**Comment by ljharb** [comment]
Referencing https://github.com/creationix/nvm/pull/616

**Comment by kenperkins** [comment]
@rvagg it seems this can be closed now?
