### ISSUE TITLE
Jenkins down?

### ISSUE THREAD

**Issue by saghul** [iojs/build#27]
I'm trying to access Jenkins to test a PR but I found that the previous URL gets redirected to http://jenkins-iojs.nodesource.com/ which gives me some hello-world ngnix page.

/cc @rvagg

**Comment by rvagg** [comment]
@saghul sorry, a borked redirect put an https in front and it'll work (will fix it now). A bunch of the bots have been down and I've been taking the opportunity to redo them all, changing the name from "node-forward" to "iojs" and documenting the setup procedure in this repo for each of them. The main Windows machine went down and I can't get it back (stuck in a reboot and I haven't got a response from Rackspace about it) so I've spun up 2 more and was going to document the setup procedure properly as I do them again but I haven't got to it yet!

The ones that should be working are the containers which have been our priority recently, we've redone the way they work and now have 2 large machines running container builds for 3 x Ubuntu versions and 2 x Debian versions so far. They _should_ work for libuv but I haven't tested that yet.

Will keep you posted here.

**Comment by saghul** [comment]
Thank you so much Rod! :heart_eyes:

**Comment by saghul** [comment]
Since I'm here, looks like the parametrized build thing is no longer working, see: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+containers/4/

**Comment by rvagg** [comment]
fixed: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+containers/nodes=iojs-containers-ubuntu-trusty/5/

**Comment by saghul** [comment]
Works, thanks!
