### ISSUE TITLE
CI security

### ISSUE THREAD

**Issue by rvagg** [iojs/build#3]
From what I understand, the current Jenkins set up for Node.js and libuv run by Joyent will do builds for commits _and_ pull requests. I'm having a hard time figuring out how this can be made secure outside of the unixes with containerisation (Solaris, Linux, ... ?). The hole I see is in running builds for pull requests basically opens these boxes up to executing arbitrary code from anybody with a GitHub account which could potentially compromise the machines themselves which is a particular concern if some of these builds will end up being actual releases.

Looking for insight from people with more experience on this than me. The most common use-case for Jenkins is in-house builds rather than open source projects so I'm not sure if this comes up a whole lot.

/cc @tjfontaine @evilpacket

**Comment by bnoordhuis** [comment]
Closing, we're effectively using a whitelist now.  If someone feels strongly about this, please reopen.
