### ISSUE TITLE
libuv GYP workers stopped working

### ISSUE THREAD

**Issue by saghul** [iojs/build#35]
This is the error they give:

~~~~
+ mkdir -p build
+ cp -a /home/iojs/gyp/ build/gyp
cp: cannot stat ‘/home/iojs/gyp/’: No such file or directory
~~~~

Full console output: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/50/nodes=iojs-ubuntu1404-gyp-64/console

/cc @rvagg 

PS: Is this the right way to report issues with the build infra?

**Comment by rvagg** [comment]
ok .. I can't explain this off the top of my head but I've fixed them and they _should_ be good to go again now, give them another try

**Comment by rvagg** [comment]
oh, and yes, this is a good way to report errors, hopefully there'll be more than me that can fix them soon
