### ISSUE TITLE
Install ccache on buildbots

### ISSUE THREAD

**Issue by bnoordhuis** [iojs/build#37]
Use ccache to speed up CI builds.  The ARM buildbot in particularly is hellishly slow.

I don't know how much storage the buildbots have but if space is at a premium, it may make sense to clean out ~/.ccache once a month or so.

/cc @rvagg

**Comment by rvagg** [comment]
```
$ ccache -s
cache directory                     /home/iojs/.ccache
cache hit (direct)                  1113
cache hit (preprocessed)               0
cache miss                          1120
called for link                       11
called for preprocessing              12
unsupported source language           16
files in cache                      3363
cache size                          39.1 Mbytes
max cache size                       8.0 Gbytes
```

working well, built in less than a minute the second time with same configuration.
