### ISSUE TITLE
Remove company affiliations from README.

### ISSUE THREAD

**Issue by mikeal** [iojs/build#39]
I ran across this tweet:
```
I really don’t like the fact that in @official_iojs people have company names associated to them =[ https://t.co/UkuwQ0HO0T
tomgco sent Jan 20, 2015 
```
I think that the company affiliations send the wrong message. All these people are here of their own merit and would retain membership were they to change companies.

**Comment by bnoordhuis** [comment]
I think it's okay to give companies credit for the fact that they're paying people to work on io.js.  It also signals that it's not just a hobby project.

**Comment by rvagg** [comment]
meh, these companies are spending good money on contributing these people's time. Part of my intention here is to demonstrate that recognition is one of the rewards for paying people to work on this stuff.

Remember companies are people too, you don't want to hurt their feelings.

Oh, and that list is kind of stale, I really need to fix the readme.

**Comment by jden** [comment]
How about listing email addresses like traditional open source projects, this way companies can get implicit recognition if contributors choose to use their company email addresses?

**Comment by rvagg** [comment]
yeah, that's a way forward if this really bothers people

**Comment by mikeal** [comment]
I don't know if the email address thing does the same thing, I pretty much never list my company address.

The more I think about this the more I think it should just be up to individuals. Maybe the default is to add them without affiliation but to tell them they can add it like the others if they wish to change it. It should be up to each person how they want to be identified.

**Comment by kenperkins** [comment]
:+1: on being left up to individuals.

**Comment by wblankenship** [comment]
:+1: on being left to individuals. Perhaps people pull request in their own attribution to the readme?

**Comment by kenperkins** [comment]
README or GOVERNANCE? @wblankenship has #49 which includes collaborators as well.

**Comment by wblankenship** [comment]
The attributions are in the REAME in #49 :smile:

**Comment by kenperkins** [comment]
Hmm? :smile:

**Comment by erickbelfy** [comment]
Do not cling to classifications, all the people who help, whether companies or individuals, are important for the life of the project. That's my opinion. :+1:

**Comment by bnoordhuis** [comment]
Closing.  Looks like this has run its course and that most people are okay with company affiliations.
