### ISSUE TITLE
Sub-WG clause

### ISSUE THREAD

**Issue by wblankenship** [iojs/build#59]
We currently have one project operating as a sub-WG of the io.js Build Team WG.  Do we need something in our _GOVERNANCE.md_ file that addresses these types of groups?

**Comment by wblankenship** [comment]
Proposal for docker-iojs to become its own working group:
https://github.com/iojs/docker-iojs/issues/39

**Comment by mikeal** [comment]
Just add it as a top level working group. There's no need to make it subordinate to another group, all the working groups are expected to collaborate with each other. The only difference, and this is actually covered already in the WORKING_GROUPS, is that if a new WG is being formed and is taking some responsibility from *another* WG the charter has to get ratified by both the TC an the WG that previous had that responsibility (in this case build).

**Comment by wblankenship** [comment]
:+1:
