### ISSUE TITLE
TC Seat

### ISSUE THREAD

**Issue by mikeal** [iojs/build#7]
This just came up in the TC meeting. It would be a good idea for the build team to assign someone to sit on the TC in a "non-voting" capacity (not that we've actually brought anything to a vote yet, we've been finding a pretty easy consensus most of the time).

We'll leave it to you to figure out who that is and then we can work on finding a time that we can schedule that works for Europe, USA and wherever the build person is :)

**Comment by bnoordhuis** [comment]
I think we can close this now. :-)
