### ISSUE TITLE
The SmartOS bots don't actually build libuv

### ISSUE THREAD

**Issue by saghul** [iojs/build#70]
https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/79/nodes=iojs-smartos14-32/console

Yet success is reported.

**Comment by jbergstroem** [comment]
smartos didn't have an exception in the jenkins config. Added dependencies to hosts and fixed the config. New run here: https://jenkins-iojs.nodesource.com/job/libuv+any-pr+multi/82/

**Comment by jbergstroem** [comment]
Seems like we get a linking error at the smartos bots. I'll have a look today. At least the build seems to be executing properly -- closing.

**Comment by saghul** [comment]
Thanks Johan!
