### ISSUE TITLE
How can I build iojs on gcc version 4.1.2?

### ISSUE THREAD

**Issue by fengmk2** [iojs/build#73]
Our production server only had gcc 4.1.2 and can't upgrade gcc in some reason.
Is there possible to build io.js on these old server?

**Comment by jbergstroem** [comment]
Unfortunately not. V8 are using C++11 features and have no intention of moving back. I'd suggest you install a newer gcc or clang using your package manager.

**Comment by fengmk2** [comment]
OK, thanks!
